### ISSUE TITLE
Failed to compile in React

### ISSUE THREAD

**Issue by DouglasVDM** [ImpendingDoom28/react-beauty-2.0#1]
Your extension looks great!
I'm starting to learn React.
Working on the intro tutorial "Tic Tac Toe" , My VS Code bombs out!
My error message below:

  Line 56:1:   Expected indentation of 4 tabs but found 8 spaces   indent
  Line 57:1:   Expected indentation of 3 tabs but found 6 spaces   indent
  Line 58:1:   Expected indentation of 2 tabs but found 4 spaces   indent
  Line 59:1:   Expected indentation of 1 tab but found 2 spaces    indent
  
  Do you have any idea how I can fix this?

**Comment by ImpendingDoom28** [comment]
Hello, DouglasVDM!

Thanks for the feedback on my extension, it really means a lot to me!!

As for your mistake, it seems to me that your linter is telling you that in
your file on Lines 56-59 there are spaces inserted instead of tabs
You should remove spaces and put tabs instead

Hope that helps, thank you again for your feedback!

Your sincerely,
Sergey Mikheev

сб, 24 апр. 2021 г. в 22:29, DouglasVDM ***@***.***>:

**Comment by DouglasVDM** [comment]
Thank you, Sergey.
After a fair amount of research, I managed to modify my linter to fix the issues "on save" for React.
I wish there was a VsCode extension that allows for React code formatting.
I'm out of my comfort zone when it comes to linting.
Keep up the good work.
Regards,
Douglas
https://www.linkedin.com/in/douglas-van-der-merwe-b4552467/
